# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: produtos.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'produtos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprodutos.proto\"\x07\n\x05\x45mpty\":\n\x07Produto\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x02\x12\x12\n\nquantidade\x18\x03 \x01(\x05\"+\n\rListaProdutos\x12\x1a\n\x08produtos\x18\x01 \x03(\x0b\x32\x08.Produto\"\x1e\n\x0eProdutoRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\",\n\x0fProdutoResponse\x12\x19\n\x07produto\x18\x01 \x01(\x0b\x32\x08.Produto\"!\n\x0cPrecoRequest\x12\x11\n\tpreco_max\x18\x01 \x01(\x02\"4\n\x10\x41tualizarRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\"%\n\x11\x41tualizarResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xe8\x01\n\x0eProdutoService\x12(\n\x0eListarProdutos\x12\x06.Empty\x1a\x0e.ListaProdutos\x12\x39\n\x14\x43onsultarProdutoNome\x12\x0f.ProdutoRequest\x1a\x10.ProdutoResponse\x12\x36\n\x15\x43onsultarProdutoPreco\x12\r.PrecoRequest\x1a\x0e.ListaProdutos\x12\x39\n\x10\x41tualizarEstoque\x12\x11.AtualizarRequest\x1a\x12.AtualizarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produtos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_PRODUTO']._serialized_start=27
  _globals['_PRODUTO']._serialized_end=85
  _globals['_LISTAPRODUTOS']._serialized_start=87
  _globals['_LISTAPRODUTOS']._serialized_end=130
  _globals['_PRODUTOREQUEST']._serialized_start=132
  _globals['_PRODUTOREQUEST']._serialized_end=162
  _globals['_PRODUTORESPONSE']._serialized_start=164
  _globals['_PRODUTORESPONSE']._serialized_end=208
  _globals['_PRECOREQUEST']._serialized_start=210
  _globals['_PRECOREQUEST']._serialized_end=243
  _globals['_ATUALIZARREQUEST']._serialized_start=245
  _globals['_ATUALIZARREQUEST']._serialized_end=297
  _globals['_ATUALIZARRESPONSE']._serialized_start=299
  _globals['_ATUALIZARRESPONSE']._serialized_end=336
  _globals['_PRODUTOSERVICE']._serialized_start=339
  _globals['_PRODUTOSERVICE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
